# Generated by Django 6.0.1 on 2026-03-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='envoyee',
            field=models.BooleanField(default=False),
        ),
    ]
