# Generated by Django 6.0.1 on 2026-03-10 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0009_alter_commande_statut'),
        ('factures', '0003_alter_facture_commande_alter_facture_paiement'),
        ('paiements', '0008_alter_paiement_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='commande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='commandes.commande'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='paiement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='paiements.paiement'),
        ),
    ]
