# Generated by Django 6.0.1 on 2026-01-21 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('commandes', '0002_initial'),
        ('paiements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse_livraison',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_livraison',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='mode_paiement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paiements.modepaiement'),
        ),
        migrations.AddField(
            model_name='commande',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.produit'),
        ),
        migrations.AddField(
            model_name='commande',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(default='EN ATTENTE', max_length=50),
        ),
    ]
