# Generated by Django 6.0.1 on 2026-02-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_alter_commande_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(default='EN ATTENTE', max_length=50),
        ),
    ]
