# Generated by Django 6.0.1 on 2026-02-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0007_commandeitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('EN ATTENTE', 'En attente'), ('VALIDÉE', 'Validée'), ('ANNULÉE', 'Annulée')], default='EN ATTENTE', max_length=50),
        ),
    ]
