# Generated by Django 6.0.1 on 2026-03-18 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_produit_is_active'),
        ('commandes', '0009_alter_commande_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.produit'),
        ),
    ]
