# Generated by Django 6.0.1 on 2026-03-19 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0010_alter_details_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='quantite',
        ),
    ]
