# Generated by Django 6.0.1 on 2026-03-19 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_produit_is_active'),
        ('commandes', '0011_remove_commande_produit_remove_commande_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.produit'),
        ),
        migrations.AddField(
            model_name='commande',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
