# Generated by Django 6.0.1 on 2026-03-19 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0012_commande_produit_commande_quantite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='date_livraison',
        ),
    ]
