# Generated by Django 6.0.1 on 2026-01-21 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_commande_adresse_livraison_commande_date_livraison_and_more'),
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modepaiement',
            name='numero_assoc',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='date_paiement',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='mode',
        ),
        migrations.AddField(
            model_name='paiement',
            name='mode_paiement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paiements.modepaiement'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandes.commande'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(default='EN ATTENTE', max_length=50),
        ),
    ]
