# Generated by Django 6.0.1 on 2026-01-29 06:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_remove_modepaiement_numero_assoc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiement',
            name='preuve',
            field=models.FileField(blank=True, null=True, upload_to='preuves/'),
        ),
        migrations.AlterField(
            model_name='modepaiement',
            name='mode_paiement',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('EN ATTENTE', 'En attente'), ('VALIDÉ', 'Validé'), ('ANNULÉ', 'Annulé')], default='EN ATTENTE', max_length=50),
        ),
    ]
