# Generated by Django 6.0.1 on 2026-01-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0003_paiement_client_paiement_date_paiement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('EN ATTENTE', 'En attente'), ('REÇU', 'Reçu'), ('ANNULÉ', 'Annulé')], default='EN ATTENTE', max_length=50),
        ),
    ]
