# Generated by Django 6.0.1 on 2026-02-02 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0006_alter_commande_statut'),
        ('paiements', '0005_alter_paiement_client_alter_paiement_commande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='commande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='commandes.commande'),
        ),
    ]
