# Generated by Django 6.0.1 on 2026-02-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0006_alter_paiement_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='modepaiement',
            name='numero_admin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
