# Generated by Django 6.0.1 on 2026-03-09 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0009_alter_commande_statut'),
        ('paiements', '0007_modepaiement_numero_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='commandes.commande'),
        ),
    ]
