# Generated by Django 6.0.1 on 2026-03-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0008_alter_paiement_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
