# Generated by Django 6.0.1 on 2026-03-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0009_alter_paiement_date_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En_attente'), ('REÇU', 'Reçu'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=50),
        ),
    ]
