# Generated by Django 6.0.1 on 2026-01-15 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('type_F', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelleTP', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('stock', models.IntegerField(default=0)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='catalogue.fournisseur')),
                ('type_produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='catalogue.typeproduit')),
            ],
        ),
    ]
