# Generated by Django 6.0.1 on 2026-02-09 07:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_produit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_ajout',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
