# Generated by Django 6.0.1 on 2026-02-18 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_produit_date_ajout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='catalogue.fournisseur'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='type_produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='catalogue.typeproduit'),
        ),
    ]
