# Generated by Django 6.0.1 on 2026-02-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_alter_produit_fournisseur_alter_produit_type_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
