# Generated by Django 6.0.1 on 2026-03-26 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_produit_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='is_active',
        ),
    ]
