# Generated by Django 6.0.1 on 2026-04-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_produit_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
