# Generated by Django 6.0.1 on 2026-01-21 06:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_commande_adresse_livraison_commande_date_livraison_and_more'),
        ('livraisons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='adresse_livraison',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandes.commande'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='date_livraison',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(default='EN ATTENTE', max_length=50),
        ),
    ]
