# Generated by Django 6.0.1 on 2026-01-25 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_alter_commande_client'),
        ('livraisons', '0002_alter_livraison_adresse_livraison_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='livraison',
            old_name='adresse_livraison',
            new_name='adresse',
        ),
        migrations.AddField(
            model_name='livraison',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commandes.commande'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='date_livraison',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('VALIDÉE', 'Validée'), ('ANNULÉE', 'Annulée')], default='EN_ATTENTE', max_length=20),
        ),
    ]
