# Generated by Django 6.0.1 on 2026-02-05 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0006_alter_commande_statut'),
        ('livraisons', '0003_rename_adresse_livraison_livraison_adresse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='client',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='date_livraison',
        ),
        migrations.AddField(
            model_name='livraison',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='date_prevue',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='commande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='commandes.commande'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('NON DÉMARRÉE', 'Non démarrée'), ('EN COURS', 'En cours'), ('LIVRÉE', 'Livrée')], default='NON DÉMARRÉE', max_length=20),
        ),
    ]
