# Generated by Django 6.0.1 on 2026-03-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraisons', '0004_remove_livraison_adresse_remove_livraison_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('NON_DEMARREE', 'Non démarrée'), ('EN_COURS', 'En cours'), ('LIVREE', 'Livrée')], default='NON_DEMARREE', max_length=20),
        ),
    ]
