# Generated by Django 6.0.1 on 2026-03-09 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0009_alter_commande_statut'),
        ('livraisons', '0005_alter_livraison_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='commandes.commande'),
        ),
    ]
