# Generated by Django 6.0.1 on 2026-03-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraisons', '0006_alter_livraison_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('NON_DEMARREE', 'NON_DEMARRE'), ('EN_COURS', 'EN_COURS'), ('LIVREE', 'LIVREE')], default='NON_DEMARREE', max_length=20),
        ),
    ]
