# Generated by Django 6.0.1 on 2026-01-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_alter_utilisateur_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('ADMIN', 'Admin')], default='CLIENT', max_length=10),
        ),
    ]
