# Generated by Django 6.0.1 on 2026-01-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0006_alter_utilisateur_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='privilege',
            field=models.CharField(blank=True, choices=[('STOCKS', 'Gestion des stocks'), ('COMMANDES', 'Supervision des commandes'), ('PAIEMENTS', 'Validation des paiements'), ('GLOBAL', 'Supervision générale')], max_length=20, null=True),
        ),
    ]
