# Generated by Django 6.0.1 on 2026-01-29 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0008_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='date',
            new_name='date_creation',
        ),
    ]
