# Generated by Django 6.0.1 on 2026-03-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0009_rename_date_notification_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
