# Generated by Django 6.0.1 on 2026-03-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0010_utilisateur_suspension_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='lien',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
