# Generated by Django 6.0.1 on 2026-01-15 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('AJUSTEMENT', 'Ajustement')], max_length=20)),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('quantite', models.IntegerField()),
                ('stock_avant', models.IntegerField()),
                ('stock_apres', models.IntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='catalogue.produit')),
            ],
        ),
    ]
