# Generated by Django 6.0.1 on 2026-01-28 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_alter_commande_client'),
        ('stocks', '0003_mouvementstock_utilisateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commandes.commande'),
        ),
    ]
