# Generated by Django 6.0.1 on 2026-02-02 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_mouvementstock_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouvementstock',
            name='utilisateur',
        ),
    ]
